---
- hosts: all
  tasks:
  - name: create group
    group:
      name: star 
      state: present
  - name: create a user
    user:
      name: "{{ item }}"
      state: present
      groups: "star"
    loop:
      - 'kamal'
      - 'rajini'
