---
- hosts: all
  tasks:
  - name: Show all the hosts in the inventory
    ansible.builtin.debug:
      msg: "{{ item }}"
    loop: "{{ query('inventory_hostnames', 'all') }}"

  - name: Show all the hosts matching the pattern, ie all but the group www
    ansible.builtin.debug:
      msg: "{{ item }}"
    loop: "{{ query('inventory_hostnames', 'all:!data') }}"
